(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("nongnu" . "https://elpa.nongnu.org/nongnu/") t)
(package-initialize)

(setq gc-cons-threshold 50000000)

(add-to-list 'load-path (expand-file-name "init.d" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "init.d/packages" user-emacs-directory))

(require 'init-defaults)
(require 'init-modal)
(require 'init-rime)
(require 'init-const)
(require 'themes/init)
(require 'init-git)
(require 'init-edit)
(require 'init-file)
(require 'init-lsp)
(require 'init-custom)
(require 'init-funcs)
(require 'init-ui)
